apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    app: karsajobs-ui
    tier: frontend
spec:
  # Menentukan custom node port
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
  selector:
    app: karsajobs-ui
    tier: frontend