apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    app: karsajobs
    tier: backend
spec:
  # Menentukan custom node port
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30088
  selector:
    app: karsajobs
    tier: backend