apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  ports:
    - name: tcp-rabbitmq
      port: 5672
    - name: http-management
      port: 15672

  selector:
    app: rabbitmq