apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq-service
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: rabbitmq:3.11-management
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: tcp-rabbitmq
        - containerPort: 15672
          name: http-management
        volumeMounts:
        - name: rabbitmq-persistent-storage
          mountPath: /data/rabbitmq
      volumes:
      - name: rabbitmq-persistent-storage
        persistentVolumeClaim:
          claimName: rabbitmq-pv-claim